// Bundled Arduino IDE example sketches. Each .ino is imported verbatim (comments
// intact) via esbuild's text loader and offered in the Examples picker, where it
// is loaded into the editor and converted to blocks by the importer.
//
// Generated by scripts/gen-examples.js from the official arduino/arduino-examples
// repository. Do not edit by hand — re-run the script to update.

import ex0 from './sketches/01.Basics/AnalogReadSerial.ino';
import ex1 from './sketches/01.Basics/BareMinimum.ino';
import ex2 from './sketches/01.Basics/Blink.ino';
import ex3 from './sketches/01.Basics/DigitalReadSerial.ino';
import ex4 from './sketches/01.Basics/Fade.ino';
import ex5 from './sketches/01.Basics/ReadAnalogVoltage.ino';
import ex6 from './sketches/02.Digital/BlinkWithoutDelay.ino';
import ex7 from './sketches/02.Digital/Button.ino';
import ex8 from './sketches/02.Digital/Debounce.ino';
import ex9 from './sketches/02.Digital/DigitalInputPullup.ino';
import ex10 from './sketches/02.Digital/StateChangeDetection.ino';
import ex11 from './sketches/02.Digital/toneKeyboard.ino';
import ex12 from './sketches/02.Digital/toneMelody.ino';
import ex13 from './sketches/02.Digital/toneMultiple.ino';
import ex14 from './sketches/02.Digital/tonePitchFollower.ino';
import ex15 from './sketches/03.Analog/AnalogInOutSerial.ino';
import ex16 from './sketches/03.Analog/AnalogInput.ino';
import ex17 from './sketches/03.Analog/AnalogWriteMega.ino';
import ex18 from './sketches/03.Analog/Calibration.ino';
import ex19 from './sketches/03.Analog/Fading.ino';
import ex20 from './sketches/03.Analog/Smoothing.ino';
import ex21 from './sketches/04.Communication/ASCIITable.ino';
import ex22 from './sketches/04.Communication/Dimmer.ino';
import ex23 from './sketches/04.Communication/Graph.ino';
import ex24 from './sketches/04.Communication/Midi.ino';
import ex25 from './sketches/04.Communication/MultiSerial.ino';
import ex26 from './sketches/04.Communication/PhysicalPixel.ino';
import ex27 from './sketches/04.Communication/ReadASCIIString.ino';
import ex28 from './sketches/04.Communication/SerialCallResponse.ino';
import ex29 from './sketches/04.Communication/SerialCallResponseASCII.ino';
import ex30 from './sketches/04.Communication/SerialEvent.ino';
import ex31 from './sketches/04.Communication/SerialPassthrough.ino';
import ex32 from './sketches/04.Communication/VirtualColorMixer.ino';
import ex33 from './sketches/05.Control/Arrays.ino';
import ex34 from './sketches/05.Control/ForLoopIteration.ino';
import ex35 from './sketches/05.Control/IfStatementConditional.ino';
import ex36 from './sketches/05.Control/switchCase.ino';
import ex37 from './sketches/05.Control/switchCase2.ino';
import ex38 from './sketches/05.Control/WhileStatementConditional.ino';
import ex39 from './sketches/06.Sensors/ADXL3xx.ino';
import ex40 from './sketches/06.Sensors/Knock.ino';
import ex41 from './sketches/06.Sensors/Memsic2125.ino';
import ex42 from './sketches/06.Sensors/Ping.ino';
import ex43 from './sketches/07.Display/barGraph.ino';
import ex44 from './sketches/07.Display/RowColumnScanning.ino';
import ex45 from './sketches/08.Strings/CharacterAnalysis.ino';
import ex46 from './sketches/08.Strings/StringAdditionOperator.ino';
import ex47 from './sketches/08.Strings/StringAppendOperator.ino';
import ex48 from './sketches/08.Strings/StringCaseChanges.ino';
import ex49 from './sketches/08.Strings/StringCharacters.ino';
import ex50 from './sketches/08.Strings/StringComparisonOperators.ino';
import ex51 from './sketches/08.Strings/StringConstructors.ino';
import ex52 from './sketches/08.Strings/StringIndexOf.ino';
import ex53 from './sketches/08.Strings/StringLength.ino';
import ex54 from './sketches/08.Strings/StringLengthTrim.ino';
import ex55 from './sketches/08.Strings/StringReplace.ino';
import ex56 from './sketches/08.Strings/StringStartsWithEndsWith.ino';
import ex57 from './sketches/08.Strings/StringSubstring.ino';
import ex58 from './sketches/08.Strings/StringToInt.ino';
import ex59 from './sketches/09.USB/ButtonMouseControl.ino';
import ex60 from './sketches/09.USB/JoystickMouseControl.ino';
import ex61 from './sketches/09.USB/KeyboardAndMouseControl.ino';
import ex62 from './sketches/09.USB/KeyboardLogout.ino';
import ex63 from './sketches/09.USB/KeyboardMessage.ino';
import ex64 from './sketches/09.USB/KeyboardReprogram.ino';
import ex65 from './sketches/09.USB/KeyboardSerial.ino';
import ex66 from './sketches/10.StarterKit_BasicKit/p02_SpaceshipInterface.ino';
import ex67 from './sketches/10.StarterKit_BasicKit/p03_LoveOMeter.ino';
import ex68 from './sketches/10.StarterKit_BasicKit/p04_ColorMixingLamp.ino';
import ex69 from './sketches/10.StarterKit_BasicKit/p05_ServoMoodIndicator.ino';
import ex70 from './sketches/10.StarterKit_BasicKit/p06_LightTheremin.ino';
import ex71 from './sketches/10.StarterKit_BasicKit/p07_Keyboard.ino';
import ex72 from './sketches/10.StarterKit_BasicKit/p08_DigitalHourglass.ino';
import ex73 from './sketches/10.StarterKit_BasicKit/p09_MotorizedPinwheel.ino';
import ex74 from './sketches/10.StarterKit_BasicKit/p10_Zoetrope.ino';
import ex75 from './sketches/10.StarterKit_BasicKit/p11_CrystalBall.ino';
import ex76 from './sketches/10.StarterKit_BasicKit/p12_KnockLock.ino';
import ex77 from './sketches/10.StarterKit_BasicKit/p13_TouchSensorLamp.ino';
import ex78 from './sketches/10.StarterKit_BasicKit/p14_TweakTheArduinoLogo.ino';
import ex79 from './sketches/10.StarterKit_BasicKit/p15_HackingButtons.ino';
import ex80 from './sketches/11.ArduinoISP/ArduinoISP.ino';

export interface Example {
  name: string;
  description: string;
  code: string;
}

export interface ExampleCategory {
  name: string;
  examples: Example[];
}

export const exampleCategories: ExampleCategory[] = [
  {
    name: "01. Basics",
    examples: [
      { name: "AnalogReadSerial", description: "Reads an analog input on pin 0, prints the result to the Serial Monitor.", code: ex0 },
      { name: "BareMinimum", description: "BareMinimum", code: ex1 },
      { name: "Blink", description: "Turns an LED on for one second, then off for one second, repeatedly.", code: ex2 },
      { name: "DigitalReadSerial", description: "Reads a digital input on pin 2, prints the result to the Serial Monitor", code: ex3 },
      { name: "Fade", description: "This example shows how to fade an LED on pin 9 using the analogWrite()", code: ex4 },
      { name: "ReadAnalogVoltage", description: "Reads an analog input on pin 0, converts it to voltage, and prints the result to the Serial Monitor.", code: ex5 },
    ],
  },
  {
    name: "02. Digital",
    examples: [
      { name: "BlinkWithoutDelay", description: "Turns on and off a light emitting diode (LED) connected to a digital pin,", code: ex6 },
      { name: "Button", description: "Turns on and off a light emitting diode(LED) connected to digital pin 13,", code: ex7 },
      { name: "Debounce", description: "Each time the input pin goes from LOW to HIGH (e.g. because of a push-button", code: ex8 },
      { name: "DigitalInputPullup", description: "This example demonstrates the use of pinMode(INPUT_PULLUP). It reads a digital", code: ex9 },
      { name: "StateChangeDetection", description: "Often, you don't need to know the state of a digital input all the time, but", code: ex10 },
      { name: "toneKeyboard", description: "Plays a pitch that changes based on a changing analog input", code: ex11 },
      { name: "toneMelody", description: "Plays a melody", code: ex12 },
      { name: "toneMultiple", description: "Plays multiple tones on multiple pins in sequence", code: ex13 },
      { name: "tonePitchFollower", description: "Plays a pitch that changes based on a changing analog input", code: ex14 },
    ],
  },
  {
    name: "03. Analog",
    examples: [
      { name: "AnalogInOutSerial", description: "Reads an analog input pin, maps the result to a range from 0 to 255 and uses", code: ex15 },
      { name: "AnalogInput", description: "Demonstrates analog input by reading an analog sensor on analog pin 0 and", code: ex16 },
      { name: "AnalogWriteMega", description: "This sketch fades LEDs up and down one at a time on digital pins 2 through 13.", code: ex17 },
      { name: "Calibration", description: "Demonstrates one technique for calibrating sensor input. The sensor readings", code: ex18 },
      { name: "Fading", description: "This example shows how to fade an LED using the analogWrite() function.", code: ex19 },
      { name: "Smoothing", description: "Reads repeatedly from an analog input, calculating a running average and", code: ex20 },
    ],
  },
  {
    name: "04. Communication",
    examples: [
      { name: "ASCIITable", description: "Prints out byte values in all possible formats:", code: ex21 },
      { name: "Dimmer", description: "Demonstrates sending data from the computer to the Arduino board, in this case", code: ex22 },
      { name: "Graph", description: "A simple example of communication from the Arduino board to the computer: The", code: ex23 },
      { name: "Midi", description: "This sketch shows how to use the serial transmit pin (pin 1) to send MIDI note data.", code: ex24 },
      { name: "MultiSerial", description: "Receives from the main serial port, sends to the others.", code: ex25 },
      { name: "PhysicalPixel", description: "An example of using the Arduino board to receive data from the computer. In", code: ex26 },
      { name: "ReadASCIIString", description: "This sketch demonstrates the Serial parseInt() function.", code: ex27 },
      { name: "SerialCallResponse", description: "Language: Wiring/Arduino", code: ex28 },
      { name: "SerialCallResponseASCII", description: "Language: Wiring/Arduino", code: ex29 },
      { name: "SerialEvent", description: "When new serial data arrives, this sketch adds it to a String.", code: ex30 },
      { name: "SerialPassthrough", description: "Some boards, like the Arduino 101, the MKR1000, Zero, or the Micro, have one", code: ex31 },
      { name: "VirtualColorMixer", description: "their values serially. The Processing and Max/MSP programs at the bottom take", code: ex32 },
    ],
  },
  {
    name: "05. Control",
    examples: [
      { name: "Arrays", description: "Demonstrates the use of an array to hold pin numbers in order to iterate over", code: ex33 },
      { name: "ForLoopIteration", description: "Demonstrates the use of a for() loop.", code: ex34 },
      { name: "IfStatementConditional", description: "This example demonstrates the use of if() statements.", code: ex35 },
      { name: "switchCase", description: "Demonstrates the use of a switch statement. The switch statement allows you", code: ex36 },
      { name: "switchCase2", description: "Demonstrates the use of a switch statement. The switch statement allows you", code: ex37 },
      { name: "WhileStatementConditional", description: "This example demonstrates the use of while() statements.", code: ex38 },
    ],
  },
  {
    name: "06. Sensors",
    examples: [
      { name: "ADXL3xx", description: "Reads an Analog Devices ADXL3xx accelerometer and communicates the", code: ex39 },
      { name: "Knock", description: "This sketch reads a piezo element to detect a knocking sound.", code: ex40 },
      { name: "Memsic2125", description: "Read the Memsic 2125 two-axis accelerometer. Converts the pulses output by the", code: ex41 },
      { name: "Ping", description: "This sketch reads a PING))) ultrasonic rangefinder and returns the distance", code: ex42 },
    ],
  },
  {
    name: "07. Display",
    examples: [
      { name: "barGraph", description: "Turns on a series of LEDs based on the value of an analog sensor.", code: ex43 },
      { name: "RowColumnScanning", description: "This example controls an 8x8 LED matrix using two analog inputs.", code: ex44 },
    ],
  },
  {
    name: "08. Strings",
    examples: [
      { name: "CharacterAnalysis", description: "Examples using the character analysis operators.", code: ex45 },
      { name: "StringAdditionOperator", description: "Examples of how to add Strings together", code: ex46 },
      { name: "StringAppendOperator", description: "Examples of how to append different data types to Strings", code: ex47 },
      { name: "StringCaseChanges", description: "Examples of how to change the case of a String", code: ex48 },
      { name: "StringCharacters", description: "Examples of how to get and set characters of a String", code: ex49 },
      { name: "StringComparisonOperators", description: "Examples of how to compare Strings using the comparison operators", code: ex50 },
      { name: "StringConstructors", description: "Examples of how to create Strings from other data types", code: ex51 },
      { name: "StringIndexOf", description: "Examples of how to evaluate, look for, and replace characters in a String", code: ex52 },
      { name: "StringLength", description: "Examples of how to use length() in a String.", code: ex53 },
      { name: "StringLengthTrim", description: "Examples of how to use length() and trim() in a String", code: ex54 },
      { name: "StringReplace", description: "Examples of how to replace characters or substrings of a String", code: ex55 },
      { name: "StringStartsWithEndsWith", description: "Examples of how to use startsWith() and endsWith() in a String", code: ex56 },
      { name: "StringSubstring", description: "Examples of how to use substring in a String", code: ex57 },
      { name: "StringToInt", description: "Reads a serial input string until it sees a newline, then converts the string", code: ex58 },
    ],
  },
  {
    name: "09. USB",
    examples: [
      { name: "ButtonMouseControl", description: "For Leonardo and Due boards only.", code: ex59 },
      { name: "JoystickMouseControl", description: "Controls the mouse from a joystick on an Arduino Leonardo, Micro or Due.", code: ex60 },
      { name: "KeyboardAndMouseControl", description: "Controls the mouse from five pushbuttons on an Arduino Leonardo, Micro or Due.", code: ex61 },
      { name: "KeyboardLogout", description: "This sketch demonstrates the Keyboard library.", code: ex62 },
      { name: "KeyboardMessage", description: "For the Arduino Leonardo and Micro.", code: ex63 },
      { name: "KeyboardReprogram", description: "This sketch demonstrates the Keyboard library.", code: ex64 },
      { name: "KeyboardSerial", description: "For the Arduino Leonardo, Micro or Due", code: ex65 },
    ],
  },
  {
    name: "10. StarterKit BasicKit",
    examples: [
      { name: "p02_SpaceshipInterface", description: "Project 2 - Spaceship Interface", code: ex66 },
      { name: "p03_LoveOMeter", description: "Project 3 - Love-O-Meter", code: ex67 },
      { name: "p04_ColorMixingLamp", description: "Project 4 - Color Mixing Lamp", code: ex68 },
      { name: "p05_ServoMoodIndicator", description: "Project 5 - Servo Mood Indicator", code: ex69 },
      { name: "p06_LightTheremin", description: "Project 6 - Light Theremin", code: ex70 },
      { name: "p07_Keyboard", description: "Project 7 - Keyboard", code: ex71 },
      { name: "p08_DigitalHourglass", description: "Project 8 - Digital Hourglass", code: ex72 },
      { name: "p09_MotorizedPinwheel", description: "Project 9 - Motorized Pinwheel", code: ex73 },
      { name: "p10_Zoetrope", description: "Project 10 - Zoetrope", code: ex74 },
      { name: "p11_CrystalBall", description: "Project 11 - Crystal Ball", code: ex75 },
      { name: "p12_KnockLock", description: "Project 12 - Knock Lock", code: ex76 },
      { name: "p13_TouchSensorLamp", description: "Project 13 - Touch Sensor Lamp", code: ex77 },
      { name: "p14_TweakTheArduinoLogo", description: "Project 14 - Tweak the Arduino Logo", code: ex78 },
      { name: "p15_HackingButtons", description: "Project 15 - Hacking Buttons", code: ex79 },
    ],
  },
  {
    name: "11. ArduinoISP",
    examples: [
      { name: "ArduinoISP", description: "ArduinoISP", code: ex80 },
    ],
  },
];
